packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  sharp: false
ignoredBuiltDependencies:
  - unrs-resolver
minimumReleaseAgeExclude:
  - "@types/node@26.1.0"
