name = "poketistix-docs-search"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "poketistix-docs"
database_id = "f5cf3f22-f5c5-4845-a51f-20e06b24452d"
