name = "pokemetrix-docs-search"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "pokemetrix-docs"
database_id = "4bb775a3-6d30-4e0d-ab45-b7c11b7122cc"
