name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  build:
    name: Build/Format/Lint/Test
    environment: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v7
      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: ./package.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Enable Corepack
        run: corepack enable

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v6
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "packages/damage-calc"

      - name: Build WebAssembly
        run: pnpm --filter @pokemetrix/damage-calc run build

      - name: Generate content-collections
        run: pnpm --filter @pokemetrix/app exec content-collections build

      - name: Lint
        run: pnpm lint

      - name: Check i18n keys
        run: pnpm --filter @pokemetrix/app run i18n:check

      - name: Build Next.js App
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
        run: pnpm build:app

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Test WebAssembly (Chrome)
        run: wasm-pack test --headless --chrome packages/damage-calc

      - name: Test WebAssembly (Firefox)
        run: wasm-pack test --headless --firefox packages/damage-calc

      - name: Test Rust (cargo nextest)
        run: |
          cd packages/damage-calc
          cargo nextest run --profile ci

      - name: Test Next.js (Vitest)
        env:
          NODE_ENV: test
        run: pnpm --filter @pokemetrix/app run test:ci

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/test-results/*.xml'
